Add travis scripts
stollgr/wiremock-scenario-templating pull request #6
Opened 2017-10-30 19:44 UTC by cameronbowie

2017-10-30 20:03 UTC, cameronbowie commented
This will be used by the SDK's in Travis as follows:

1. The SDK travis job will clone this repo
2. Travis will run the install script
     a. The install script will download the latest release (based on a fixed URL) from this repo
     b. The install script will extract the ZIP
3. Travis will run the start script
     a. The start script will start wiremock in the background
4. Travis will run the tests

2017-10-31 16:29 UTC, stollgr commented on travis_scripts/install_wiremock.sh
> +RELEASE_DOWNLOAD_URL='https://github.com/stollgr/wiremock-scenario-templating/releases/download/0.12/Smartsheet-WireMock-Bundle.zip'
Is there a way to use the github repo that is kicking off the travis run? I don't want the script to be hard coded to my specific repo.

2017-10-31 16:31 UTC, stollgr requested changes
The hardcoded repo URL should be inferred from the Travis that is running the scripts. Is this possible?

2017-10-31 20:03 UTC, stollgr approved these changes

2017-10-31 20:04 UTC, merged